# Gemfile
# Rails API 模式项目依赖配置

source 'https://rubygems.org'

ruby '>= 3.3.0'

# Rails 框架
gem 'rails', '~> 7.2.0'

# 数据库
gem 'pg', '>= 1.5'

# API 相关
gem 'jwt', '~> 2.8'           # JSON Web Token，用于 API 认证
gem 'bcrypt', '~> 3.1'        # 密码加密

# JSON 处理
gem 'oj', '~> 3.18'           # 高速 JSON 解析器
gem 'active_model_serializers', '~> 0.10'  # API 序列化

# 分页
gem 'pagy', '~> 9.0'          # 分页插件

# 开发环境
group :development, :test do
  gem 'debug', platforms: %i[mri mingw x64_mingw]
  gem 'rspec-rails', '~> 6.0'
  gem 'factory_bot_rails', '~> 6.4'
  gem 'faker', '~> 3.3'
end

group :development do
  gem 'rubocop', '>= 1.60'
end
